spring.application.name=database
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres.ywwcsnxcetcsvdzxclts
spring.datasource.password=@Elementopia2.0
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#jwt.secret=mySuperSecureSecretKey123! //add custom secret key if needed
server.port=${PORT:8080}
